chembl_requester:
  host:  # e.g. localhost
  user:  # your PostgreSQL username
  password:  # your PostgreSQL password
  dbname:  # e.g. chembl_36

out_dir: out_FEP4
pipeline:
  # The following 3 does not matter when reproducing FEP+ 4 results
  tanimoto_threshold: 0.35
  year_val_start: 2023
  year_test_start: 2024
  keep_discard_not_novel: true  # Needs to be set to true when reproducing the FEP+ 4 results
  n_jobs: -1   # parallel workers for fingerprint and compounds similarity computation: -1 -> use all cores
  activity_limit: null
  filter_val_and_test_sets:  null  # We want to keep all the data as split will happen later
