chembl_requester:
  host:      # e.g. localhost
  user:      # your PostgreSQL username
  password:  # your PostgreSQL password
  dbname:    # e.g. chembl_36

# Root output directory. Final outputs go here
out_dir: out

pipeline:
  test_set_similarity_bins:
  # Assay-level mean-max Tanimoto bins (low / medium / high).
  # hi: 1.001 formats as "1.00" so the label is sim_0.66_1.00 and includes sim==1.0.
    - low: 0.0
      hi: 0.33
    - low: 0.33
      hi: 0.66
    - low: 0.66
      hi: 1.001

  # Year boundaries for the time split.
  year_val_start: 2022
  year_test_start: 2023

  split_val_like_test: true  # should we split val by similarity like test? Useful to ensure no leakage in your val set

  n_jobs: -1   # parallel workers for fingerprint and compounds similarity computation: -1 -> use all cores
  activity_limit: null  # set to an integer (e.g. 10000) for a smaller test run; null = full dataset
  filter_val_and_test_sets:  # Disable by setting to null/false
    apply_to: ["test", "val"]  # which splits you want to apply this filter to
    only_equal_relation: true  # Whether to only keep pchembl_relation of `=`
    min_std: 0.5  # Assays with fewer than this standard deviation are removed
    min_cpd_per_assay: 10  # Assays with fewer than this number of compounds are removed
    one_assay_per_doc: true  # Whether to only keep one assay per ChEMBL document
